db.getCollection('sites').find({$and:
    [
        {
            SiteDescription:{$regex:".*.*"}
        },
        {
            "SiteService.Taxonomy":
            {
                $elemMatch:{
                    "Code.who":{
                        $eq:"Youth"
                    }
                }
            }
        }
    ]
})